<?php
/**
 * @var Amasty\FrdljModule\Block\Form $block
 */
?>
<form action="<?php echo $block->getFormAction() ?>" method="post">

        <input type="text" name="sku" placeholder="sku"/>


    <?php if ($block->isFieldEnabled()) {
    ?>
    <input type="number" name="qty" placeholder="<?= $block->getFieldText() ?>"/>
        <?php
    }
    ?>
    <div>
        <p>
            <?= $block->getChildHtml('FrdljModule.timeleft') ?>
        </p>
    </div>
    <input type="submit"/>
</form>
